<?xml version="1.0" encoding="utf-8"?><Database Name="WareHouseAccounting" Class="DCAccountancyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=WareHouseAccounting;Integrated Security=True" SettingsObjectName="WareHouse_Accounting.Properties.Settings" SettingsPropertyName="WareHouseAccountingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Settings" Member="Settings">
    <Type Name="Setting" Id="ID1" Modifier="Sealed">
      <Column Name="Setiing_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AddressOfInvoices" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WarehouseRemittanceAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ContactNumberOfInvoices" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="WarehouseRemittanceContactNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SMSPanelUserName" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SMSPanelPassword" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SMSRecipientNumber" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="SMSSender" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="WarningCameFrom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WarningCameTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SendSMSForTransactions" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SendSMSForInvoices" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastEditDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role" Id="ID2" Modifier="Sealed">
      <Column Name="Role_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DepotPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BankPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PersonPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FactorPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SettingPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UserPermission" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastEditDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Role_User" Member="Users" ThisKey="Role_Id" OtherKey="Role_Id" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User" Id="ID3" Modifier="Sealed">
      <Column Name="Users_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Role_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastEditDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Role_User" Member="Role" ThisKey="Role_Id" OtherKey="Role_Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.FiLLSettings" Method="FiLLSettings">
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.InsertSettings" Method="InsertSettings">
    <Parameter Name="CompanyName" Parameter="companyName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="AddressOfInvoices" Parameter="addressOfInvoices" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="WarehouseRemittanceAddress" Parameter="warehouseRemittanceAddress" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ContactNumberOfInvoices" Parameter="contactNumberOfInvoices" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="WarehouseRemittanceContactNumber" Parameter="warehouseRemittanceContactNumber" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="SMSPanelUserName" Parameter="sMSPanelUserName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="SMSPanelPassword" Parameter="sMSPanelPassword" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="SMSRecipientNumber" Parameter="sMSRecipientNumber" Type="System.String" DbType="NVarChar(11)" />
    <Parameter Name="SMSSender" Parameter="sMSSender" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="WarningCameFrom" Parameter="warningCameFrom" Type="System.Int32" DbType="Int" />
    <Parameter Name="WarningCameTo" Parameter="warningCameTo" Type="System.Int32" DbType="Int" />
    <Parameter Name="SendSMSForTransactions" Parameter="sendSMSForTransactions" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SendSMSForInvoices" Parameter="sendSMSForInvoices" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LastEditDateTime" Parameter="lastEditDateTime" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateSettings" Method="UpdateSettings">
    <Parameter Name="CompanyName" Parameter="companyName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="AddressOfInvoices" Parameter="addressOfInvoices" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="WarehouseRemittanceAddress" Parameter="warehouseRemittanceAddress" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="ContactNumberOfInvoices" Parameter="contactNumberOfInvoices" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="WarehouseRemittanceContactNumber" Parameter="warehouseRemittanceContactNumber" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="SMSPanelUserName" Parameter="sMSPanelUserName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="SMSPanelPassword" Parameter="sMSPanelPassword" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="SMSRecipientNumber" Parameter="sMSRecipientNumber" Type="System.String" DbType="NVarChar(11)" />
    <Parameter Name="SMSSender" Parameter="sMSSender" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="WarningCameFrom" Parameter="warningCameFrom" Type="System.Int32" DbType="Int" />
    <Parameter Name="WarningCameTo" Parameter="warningCameTo" Type="System.Int32" DbType="Int" />
    <Parameter Name="SendSMSForTransactions" Parameter="sendSMSForTransactions" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SendSMSForInvoices" Parameter="sendSMSForInvoices" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LastEditDateTime" Parameter="lastEditDateTime" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExistSettings" Method="ExistSettings">
    <Parameter Name="Exist" Parameter="exist" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteRoles" Method="DeleteRoles">
    <Parameter Name="Role_Id" Parameter="role_Id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExistRoles" Method="ExistRoles">
    <Parameter Name="Exist" Parameter="exist" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillRolesByRoleID" Method="FillRolesByRoleID">
    <Parameter Name="Role_Id" Parameter="role_Id" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.InsertRoles" Method="InsertRoles">
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DepotPermission" Parameter="depotPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="BankPermission" Parameter="bankPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PersonPermission" Parameter="personPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FactorPermission" Parameter="factorPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SettingPermission" Parameter="settingPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserPermission" Parameter="userPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LastEditDateTime" Parameter="lastEditDateTime" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillRoles" Method="FillRoles">
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.UpdateRoles" Method="UpdateRoles">
    <Parameter Name="RolesId" Parameter="rolesId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="DepotPermission" Parameter="depotPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="BankPermission" Parameter="bankPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PersonPermission" Parameter="personPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="FactorPermission" Parameter="factorPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="SettingPermission" Parameter="settingPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="UserPermission" Parameter="userPermission" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="LastEditDateTime" Parameter="lastEditDateTime" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExistUsers" Method="ExistUsers">
    <Parameter Name="Exist" Parameter="exist" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckPassword" Method="CheckPassword">
    <Parameter Name="Check" Parameter="check" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteUsers" Method="DeleteUsers">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ExistUsers" Method="ExistUsers1">
    <Parameter Name="Exist" Parameter="exist" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.FillUsers" Method="FillUsers">
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.FillUsersById" Method="FillUsersById">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.InsertUsers" Method="InsertUsers">
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastEditDateTime" Parameter="lastEditDateTime" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateUsers" Method="UpdateUsers">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleId" Parameter="roleId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="LastEditDateTime" Parameter="lastEditDateTime" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CheckUserName" Method="CheckUserName">
    <Parameter Name="Check" Parameter="check" Type="System.Boolean" DbType="Bit" Direction="InOut" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>